<?php
/*
 * RyzomRenderingService - https://github.com/nimetu/rrs_client.git
 * Copyright (c) 2014 Meelis Mägi <nimetu@gmail.com>
 *
 * This file is part of RyzomRenderingService.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Rrs\Socket;

use Nel\Misc\MemStream;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-06-02 at 14:15:04.
 */
class CallbackMessageTest extends \PHPUnit_Framework_TestCase
{

    public function testSerialOut()
    {
        $buf = "\x05\x00\x00\x00"."WRITE"."payload";
        $payload = 'payload';

        $message = new CallbackMessage('WRITE');
        $message->setPayload($payload);

        $out = new MemStream();
        $message->serial($out);

        $this->assertEquals('WRITE', $message->getName());
        $this->assertEquals('payload', $message->getPayload());
        $this->assertEquals($buf, $out->getBuffer());
    }

    public function testSerialIn()
    {
        $buf = "\x04\x00\x00\x00"."READ"."payload";

        $in = new MemStream($buf);

        $message = new CallbackMessage();
        $message->serial($in);

        $this->assertEquals('READ', $message->getName());
        $this->assertEquals('payload', $message->getPayload());
    }
}
